language: php

php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"

before_script:
    - composer install
    - mysql -e 'create database dblinker_test;'

script:
    - vendor/bin/behat

env:
    - DBLINKER_DB_1_ENV_MYSQL_DATABASE=dblinker_test DBLINKER_DB_1_PORT_3306_TCP_ADDR=127.0.0.1 DBLINKER_DB_1_ENV_MYSQL_USER=travis DBLINKER_DB_1_ENV_MYSQL_PASSWORD=

matrix:
    allow_failures:
        - php: "7.0"
