language: php

php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"

before_script:
    - composer install
    - mysql -e 'create database dblinker_test;'
    - mysql -e 'create database forbidden_db;'
    - mysql -e 'CREATE USER "behat"@"localhost" IDENTIFIED BY "behatpassword";'
    - mysql -u root -e 'GRANT ALL PRIVILEGES ON dblinker_test.* TO "behat"@"localhost";'
    - mysql -u root -e 'FLUSH PRIVILEGES;'

script:
    - vendor/bin/behat -s $BEHAT_DB_DRIVER --tags ~@skip-travis

env:
    - BEHAT_DB_DRIVER=mysqli DBLINKER_DB_1_ENV_MYSQL_DATABASE=dblinker_test DBLINKER_DB_1_PORT_3306_TCP_ADDR=127.0.0.1 DBLINKER_DB_1_ENV_MYSQL_USER=behat DBLINKER_DB_1_ENV_MYSQL_PASSWORD=behatpassword DBLINKER_DB_1_ENV_MYSQL_ROOT_PASSWORD=
    - BEHAT_DB_DRIVER=pdo_mysql DBLINKER_DB_1_ENV_MYSQL_DATABASE=dblinker_test DBLINKER_DB_1_PORT_3306_TCP_ADDR=127.0.0.1 DBLINKER_DB_1_ENV_MYSQL_USER=behat DBLINKER_DB_1_ENV_MYSQL_PASSWORD=behatpassword DBLINKER_DB_1_ENV_MYSQL_ROOT_PASSWORD=

matrix:
    allow_failures:
        - php: "7.0"
    fast_finish: true
